apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-keys
  namespace: deployer-dev
data:
  id_ed25519: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBk/JNcGTMNM3XfBe/i6tYnbv/mrSQGfNQE9QKptHaq9QAAAKDvlBzI75Qc
    yAAAAAtzc2gtZWQyNTUxOQAAACBk/JNcGTMNM3XfBe/i6tYnbv/mrSQGfNQE9QKptHaq9Q
    AAAEBJTllTNbvYqGUw3rhofe3krVZRQN3v2rR4Vt/b2l0IAWT8k1wZMw0zdd8F7+Lq1idu
    /+atJAZ81AT1Aqm0dqr1AAAAGHVidW50dUBkZXBsb3ltZW50LXNlcnZlcgECAwQF
    -----END OPENSSH PRIVATE KEY-----
