apiVersion: v1
kind: ConfigMap
metadata:
  name: servers-config
  namespace: deployer-dev
data:
  servers.json: |
    [
      {
        "ip": "172.31.6.240",
        "alias": "Server A",
        "hostname": "ip-172-31-6-240",
        "user": "ubuntu",
        "privateKeyPath": "/root/.ssh/id_ed25519"
      },
      {
        "ip": "172.31.6.187",
        "alias": "Server B",
        "hostname": "ip-172-31-6-187",
        "user": "ubuntu",
        "privateKeyPath": "/root/.ssh/id_ed25519"
      }
    ]
