apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-monitor
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - monitor.ko.unieai.com
    secretName: monitor-ko-tls
  rules:
  - host: monitor.ko.unieai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: system-monitor
            port:
              number: 80
